rem * -------------------------------------------------------------------
rem *
rem *  Purpose:  Convert a Csv File to a Cobol Data file using Cobol Copybook 
rem *   Author:  RecordEditor~CodeGen
rem * Language:  Windows bat
rem *        
rem * *------------- Keep this notice in your final code ---------------
rem * *   This code was generated by JRecord projects CodeGen program
rem * *            on the: 22 Jun 2016 7:55:5 
rem * *     from Copybook: DTAR020.cbl
rem * *           Dialect: FMT_MAINFRAME
rem * *          Template: batCbl2Csv
rem * *             Split: SPLIT_NONE   
rem * * File Organization: IO_FIXED_LENGTH   
rem * *              Font: cp037
rem * *   
rem * *    CodeGen Author: Bruce Martin
rem * *-----------------------------------------------------------------
rem *
rem * This script uses CobolToCsv package (https://sourceforge.net/projects/coboltocsv)
rem * to do Cobol <---> Csv conversion
rem *
rem *-------------------------------------------------------------------

rem java -jar ../lib/Csv2Cobol.jar 
../lib/Csv2Cobol.bat  -C DTAR020.cbl ^
                      -Delimiter , ^
                      -Quote doublequote ^
                      -OFS Fixed_Length ^
                      -OC cp037 ^
                      -I out/DTAR020.bin.csv ^
                      -O out/DTAR020.fromcsv.bin

pause                      
